language: node_js

notifications:
  email: false

node_js:
  - '10'
  - '9'
  - '8'

after_success:
  - npm run coverage

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        script:
          - npx semantic-release
