language: node_js

notifications:
  email: false

node_js:
  - '10'
  - '9'
  - '8'

after_success:
  - npm run coverage

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

script:
  - npm run test

jobs:
  include:
    - stage: npm release
      node_js: lts/*
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        script:
          - npm run semantic-release
