language: node_js

notifications:
  email: false

node_js:
  - 8
  - 6

after_success:
  - npm run coverage

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        script:
          - npx semantic-release
